
version: '3'
services:
  databaseos:
    image: mysql:5.7
    volumes: 
      - mysql_storage:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: Adarsh
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: mydb

  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on: 
      - databaseos
    ports: 
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: databaseos
      WORDPRESS_DB_USER: Adarsh
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: mydb
    volumes: 
      - wordp_storage:/var/www/html

volumes:
  mysql_storage:
  wordp_storage:
